### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by tonmoy42** [dmhacker/facebook-message-analysis#1]
I followed your instruction and installed all dependencies. I'm running this on a Ubuntu 14.04 and my Python version is 2.7.6.

`dadmin@laptop-1:~/facebook-message-analysis$ python fbmsganalysis message.json 

Traceback (most recent call last):
 
 File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
 
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals

File "/home/dadmin/facebook-message-analysis/fbmsganalysis/__main__.py", line 2, in <module>
    import analyzer

File "fbmsganalysis/analyzer.py", line 17, in <module>
    sentiment_analyzer = SentimentIntensityAnalyzer()

File "/usr/local/lib/python2.7/dist-packages/vaderSentiment/vaderSentiment.py", line 212, in __init__
    with open(lexicon_full_filepath, encoding='utf-8') as f:

TypeError: 'encoding' is an invalid keyword argument for this function
`

**Comment by tonmoy42** [comment]
I also tried this on an Ubuntu 16.04 machine. This is what I ran:

1. `git clone https://github.com/dmhacker/facebook-message-analysis`

2. `cd facebook-message-analysis/`

3. `sudo apt install python-pip`

4. `sudo pip install -r requirements.txt`

5. `ubuntu@ubuntu:~/facebook-message-analysis$ python fbmsganalysis sam.json`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
  ...
  File "/home/ubuntu/.local/lib/python2.7/site-packages/vaderSentiment/vaderSentiment.py", line 17, in <module>
    import requests
ImportError: No module named requests

6. `ubuntu@ubuntu:~/facebook-message-analysis$ pip install requests`

7. `ubuntu@ubuntu:~/facebook-message-analysis$ python fbmsganalysis sam.json`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  ...
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package

8. `ubuntu@ubuntu:~/facebook-message-analysis$ sudo apt-get install python-tk`

9. `ubuntu@ubuntu:~/facebook-message-analysis$ python fbmsganalysis sam.json`
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:
    import nltk
    nltk.download('stopwords')

10. `python`
 `>>>import nltk`
`>>>nltk.download('stopwords')`
`>>>quit()`

11. `ubuntu@ubuntu:~/facebook-message-analysis$ python fbmsganalysis sam.json`
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/facebook-message-analysis/fbmsganalysis/__main__.py", line 2, in <module>
    import analyzer
  File "fbmsganalysis/analyzer.py", line 17, in <module>
    sentiment_analyzer = SentimentIntensityAnalyzer()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/vaderSentiment/vaderSentiment.py", line 212, in __init__
    with open(lexicon_full_filepath, encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by tonmoy42** [comment]
I installed Python 3.6 and the issue was resolved.
